---
- name: Install redis
  yum: name=redis state=latest
  tags: redis

- name: Configure redis file
  template: src=redis.conf dest=/etc/redis.conf
  notify: Restart redis
  tags: redis

- name: Start redis service
  service: name=redis state=started
  tags: redis
