- name: Copy hostname.sh to all nodes
  copy: src=hostname.sh dest=/tmp/hostname.sh
  tags: hosts

- name: Configure hostname
  shell: /usr/bin/bash /tmp/hostname.sh "{{ ansible_default_ipv4.address }}"
  tags: hosts

- name: Copy hosts to all nodes
  template: src=hosts.j2 dest=/etc/hosts
  tags: hosts
