---
- name: Install ntp
  yum: name=ntp state=latest
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntpd srevice
  tags: ntp

- name: Start ntpd seveice 
  service: name=ntpd enabled=yes state=started
  tags: ntp
