---
- name: Install haproxy
  yum: name=haproxy state=latest
  tags: haproxy

- name: Configure haproxy file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: Restart haproxy
  tags: haproxy

- name: Start haproxy service
  service: name=haproxy state=started
  tags: haproxy
